# Generated by Django 4.1.1 on 2023-04-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='hits',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='test',
            name='misses',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='test',
            name='scores',
            field=models.JSONField(default=dict),
        ),
    ]
