# Generated by Django 4.1.1 on 2023-03-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
