# Generated by Django 4.1.1 on 2023-04-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_age_profile_edad_remove_profile_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
