# Generated by Django 4.1.1 on 2023-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_rename_apellido_profile_apellidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
