# Generated by Django 4.1.1 on 2023-04-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_profile_lengua'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suspender',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
