# Generated by Django 4.1.1 on 2023-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_profile_suspender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lengua',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='suspender',
            field=models.CharField(choices=[('Sí, hablo solo el español', 'Sí'), ('No, soy bilingüe', 'No')], default='No', max_length=50),
        ),
    ]
