# Generated by Django 4.1.1 on 2023-04-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_profile_lengua_alter_profile_suspender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lengua',
            field=models.CharField(choices=[('Sí', 'Sí, hablo solo el español'), ('No', 'No, soy bilingüe')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='suspender',
            field=models.CharField(choices=[('Sí', 'Sí, he suspendido alguna vez'), ('No', 'No, no he suspendido nunca')], default='No', max_length=50),
        ),
    ]
